[package]
name = "dyndns-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
aws-config = { version = "0.8" }
aws-sdk-route53 = { version = "0.8" }
tokio = { version = "1.17", features = ["macros", "rt"] }
